### ISSUE TITLE
question: jq error

### ISSUE THREAD

**Issue by fraro** [git-developer/signal-mqtt#1]
I like this very simple approach to convert signal-cli to mqtt messages!

I'm trying to receive a message by signal-mqtt. I have copied the default topic-map file to /etc/signal-mqtt.
When a new message is coming in, the script fails with
```
jq: error: to_topic/1 is not defined at <top-level>, line 1:
to_topic($pattern)

```
I have not fully understood the jq command parameters, but I think it expects "to_topic" on the incoming RPC message?
Any idea?
My JSON-RPC message looks like
`{"jsonrpc":"2.0","method":"receive","params":{"envelope":{"source":"+491xxxx","sourceNumber":"+491xxxx","sourceUuid":"xxx","sourceName":"xxx","sourceDevice":1,"timestamp":1708519360910,"dataMessage":{"timestamp":1708519360910,"message":"testmessage","expiresInSeconds":0,"viewOnce":false}},"account":"+49xxxx"}}`
Thanks!

**Comment by git-developer** [comment]
Thanks for your interest.

> I have copied the default topic-map file to /etc/signal-mqtt.

That should not be necessary. Do you run a container via docker compose as documented?

**Comment by fraro** [comment]
No, it's quite stupid to fire up a container to run a bash script. But ok, I will give it a try...

**Comment by git-developer** [comment]
Have you been able to solve your problem?

**Comment by fraro** [comment]
It's working with the supplied container build. I'll check the jq version for changes, the Debian 12 seems is a bit older. Will post the result. Thanks!

**Comment by git-developer** [comment]
You're welcome.
